  - name: "creating ec2 and route 53 records"
    hosts: local
    connection: local
    become : yes
    vars: 
      AMI_ID: ami-09c813fb71547fc4f
      SG_ID: sg-0494b89cb6d5db382
      ZONE_ID: "Z01261487TFX8V684K99"
      DOMAIN_NAME: "saws86s.fun"
      instance:
       - mongodb

    tasks:

    - name: Install AWS Python libraries
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3.9
      loop:
      - boto3
      - botocore
    - name: "creating ec2 instace"
      amazon.aws.ec2_instance:
          name: "{{ item }}"
          instance_type: t3.micro
          security_group: "{{SG_ID}}"
          image_id: "{{AMI_ID}}"
          aws_region: us-east-1
          tags:
            name: "{{ item }}"
      loop: "{{instance}}"
      register: ec2_output
    - name: "printing ec2 details"
      ansible.builtin.debug:
         msg: "{{ec2_output}}"
