  - name: "creating ec2 and route 53 records"
    hosts: local
    connection: local
    
    vars: 
      ami_id: ami-09c813fb71547fc4f
      sg_id: sg-0494b89cb6d5db382
      ZONE_ID: "Z01261487TFX8V684K99"
      DOMAIN_NAME: "saws86s.fun"
       # we can pass instances through command line using -e
      instances: 
      #- mongodb
      #- redis
      #- mysql
      #- rabbitmq
       #- catalogue
      
      
    tasks:
     - name: create ec2 instance
       amazon.aws.ec2_instance:
         name: "{{ item }}"
         instance_type: t3.micro
         security_group: "{{ sg_id }}"
         image_id: "{{ ami_id }}"
         region: us-east-1
         tags:
           Name: "{{ item }}"
       loop: "{{ instances }}"
       register: ec2_output

    # - name: print the ec2_output
    #   ansible.builtin.debug:
     #    msg: "{{ ec2_output }}"
     #- name: print public address
      #  msg: "{{item.instances[0].public_ip_address}}"
       #loop: "{{ec2_output.results}}"
    # - name: print private ip address
    #   ansible.builtin.debug:
    #     msg: "{{item.instances[0].private_ip_address}}"
    #   loop: "{{ec2_output.results}}"
     - name: create route 53 records
       amazon.aws.route53:
        state: present
        zone: "{{ DOMAIN_NAME }}"
        record: "{{item.item}}.{{DOMAIN_NAME}}"
        type: A
        ttl: 1
        value: "{{item.instances[0].private_ip_address}}"
        overwrite: true
       loop: "{{ec2_output.results}}"

 