  - name: "mongodb configuration"
    hosts: mongodb
    become: yes
    tasks:
      - name: "copyting mongo repo"
        ansible.builtin.copy:
         src: mongo.repo
         dest: /etc/yum.repos.d/mongo.repo
      - name: "installing mongodb"
        ansible.builtin.package:
          name: mongodb-org
          state: present
      - name: "start and enable service"
        ansible.builtin.service:
          name: mongod
          state: started
          enabled: yes
      - name: "opening remote connections"
        ansible.builtin.replace:
          path: /etc/mongod.conf
          regexp: "127.0.0.1"
          replace: "0.0.0.0"
      - name: Restart service httpd, in all cases
        ansible.builtin.service:
          name: mongod
          state: restarted