  - name: setup for payment server
    hosts: payment
    become: yes
    tasks:
      - name: "install python packages"
        ansible.builtin.dnf:
         name: "{{ item }}"
         state: present
        loop:
         - python
         - gcc
         - python3-devel

      - name: "create system user"
        ansible.builtin.user:
         name: roboshop
         shell: /sbin/nologin
         system: true
         comment: "roboshop system user"
         home: /app
## deleteing /app directory if run second time creates new one
      - name: "create app directory"
        ansible.builtin.file:
         path: /app
         state: absent

      - name: "create app directory"
        ansible.builtin.file:
         path: /app
         state: directory

      - name: "delete previous code"
        ansible.builtin.file:
         path: /tmp/payment.zip
         state: absent
      - name: Download payment code
        ansible.builtin.get_url:
         url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
         dest: /tmp/payment.zip

      - name: unzip payment code in /app
        ansible.builtin.unarchive:
          src: /tmp/payment.zip
          dest: /app
          remote_src: yes

      - name: install dependencies
        ansible.builtin.pip:
          requirements: requirements.txt
          executable: pip3.9
          args:
            chdir: /app
      - name: copy payment service file
        ansible.builtin.copy:
          src: payment.service
          dest: /etc/systemd/system/payment.service

      - name: "start ,enable and daemon reload user"
        ansible.builtin.service:
         name: user
         state: started
         enabled: yes
         daemon_reload: yes